### ISSUE TITLE
"navigator.getUserMedia is not a function" when trying to create rooms in the latest master [as of 16th Mar 2022]

### ISSUE THREAD

**Issue by manjurajv** [muaz-khan/RTCMultiConnection-Server#37]
Uncaught TypeError: navigator.getUserMedia is not a function
    at getUserMediaHandler (RTCMultiConnection.min.js:16:5245)
    at RTCMultiConnection.connection.invokeGetUserMedia (RTCMultiConnection.min.js:18:8054)
    at RTCMultiConnection.connection.getUserMedia.connection.captureUserMedia (RTCMultiConnection.min.js:17:31467)
    at RTCMultiConnection.min.js:17:27046
    at RTCMultiConnection.min.js:17:18061
    at Socket.<anonymous> (RTCMultiConnection.min.js:15:7104)
    at Socket.Emitter.emit (index.js:143:20)
    at Socket.onconnect (socket.js:323:14)
    at Socket.onpacket (socket.js:221:26)
    at Manager.Emitter.emit (index.js:143:20)

**Comment by manjurajv** [comment]
Browser used is "Version 99.0.4844.51 (Official Build) snap (64-bit)"
PC: Linux curiosity 5.4.0-104-generic #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

https://stackoverflow.com/questions/28991835/firefox-navigator-getusermedia-is-not-a-function
Let me know where the changes are to be done.
